services:
  server:
    build:
      context: .
    ports:
      - 5001:5001
    volumes:
      - ./processing:/app/processing
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
